WIP: Add write capability to PilzModbusReadClient
PilzDE/pilz_robots pull request #132
Opened 2019-05-23 09:27 UTC by hslusarek

2019-06-03 12:48 UTC, ct2034 requested changes

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/include/prbt_hardware_support/libmodbus_client.h
> -  /**
Please add all the documentation again

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/include/prbt_hardware_support/param_names.h
>  static const std::string PARAM_MODBUS_TOPIC_NAME_STR {"modbus_topic_name"};
rename this to PARAM_MODBUS_READ_TOPIC_NAME_STR
Not sure about  the topic name itself. maybe it should stay like this, for compatibility. Maybe do a search and replace in the repo to do modbus_topic_name -> modbus_read_topic_name"

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/include/prbt_hardware_support/pilz_modbus_client_exception.h
> +#endif // PRBT_HARDWARE_SUPPORT_READ_CLIENT_EXCEPTION_H
change the precompiler variable PRBT_HARDWARE_SUPPORT_READ_CLIENT_EXCEPTION_H -> PRBT_HARDWARE_SUPPORT_MODBUS_CLIENT_EXCEPTION_H

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/src/pilz_modbus_client_node.cpp
>    ROS_DEBUG_STREAM("Number of registers to read: " << num_registers_to_read
are they only to read? or also to write?
if 1) add debug output for write
if 2) change variable name

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/test/include/prbt_hardware_support/pilz_modbus_client_mock.h
> +                                                               const int read_addr, const int read_nb));
add newline between arguments to match style

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/src/pilz_modbus_client_node.cpp
>  {
ros::init(argc, argv, "modbus_read_node");
->   ros::init(argc, argv, "modbus_client_node"); (or whatever)

2019-06-03 12:48 UTC, ct2034 commented on prbt_hardware_support/include/prbt_hardware_support/modbus_topic_definitions.h
> +static const std::string TOPIC_MODBUS_WRITE = "/pilz_modbus_node/modbus_write";
update documentation in prbt_hardware_support/README.md

2019-07-04 06:10 UTC, hslusarek commented
@ct2034 Please do not force push on branches on which other people work on! If you want to change something, then do a normal commit and push it. Otherwise, synchronize yourself with the people which work on the branches.

2019-07-04 10:41 UTC, merged