Feature/hold at braketest
PilzDE/pilz_robots pull request #138
Opened 2019-06-06 08:05 UTC by martiniil

* Enter hold mode at braketest execution
* Revise documentation of prbt_hardware_support

2019-06-18 11:22 UTC, hslusarek requested changes
Looks good, only a few minor improvement suggestions.

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/src/brake_test_executor.cpp
> +  if (!controller_hold_client_.waitForExistence(ros::Duration(WAIT_FOR_SERVICE_TIMEOUT_S)))
It was stated by @jschleicher that it is uncommon in ROS to timeout while waiting for let's say a service. I introduced some convenience functions in my PR #135 (see [here](https://github.com/PilzDE/pilz_robots/blob/c9bf02eaa7bd02b2e7267413a81f2fcfc116e6cc/prbt_hardware_support/include/prbt_hardware_support/wait_for_service.h#L34))

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/src/brake_test_executor.cpp
> +  controller_unhold_client_ = nh_.serviceClient<std_srvs::Trigger>(CONTROLLER_UNHOLD_MODE_SERVICE_NAME);
It was stated by @jschleicher that it is uncommon in ROS to timeout while waiting for let's say a service. I introduced some convenience functions in my PR #135 (see [here](https://github.com/PilzDE/pilz_robots/blob/c9bf02eaa7bd02b2e7267413a81f2fcfc116e6cc/prbt_hardware_support/include/prbt_hardware_support/wait_for_service.h#L34))

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/src/brake_test_executor.cpp
>    if (!trigger_braketest_client_.waitForExistence(ros::Duration(WAIT_FOR_SERVICE_TIMEOUT_S)))
It was stated by @jschleicher that it is uncommon in ROS to timeout while waiting for let's say a service. I introduced some convenience functions in my PR #135 (see [here](https://github.com/PilzDE/pilz_robots/blob/c9bf02eaa7bd02b2e7267413a81f2fcfc116e6cc/prbt_hardware_support/include/prbt_hardware_support/wait_for_service.h#L34))

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/README.md
> +The prbt_hardware_support package contains files supporting the safety functions STO and SBC of the PRBT manipulator,
For better understanding I would write the complete words in brackets behind the abbreviations.

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/README.md
> +To allow a controlled stop, the safety controller is allowed to delay the STO signal by several milliseconds. This package opens a
I would write: "To allow a controlled stop, the safety controller delays the STO signal by several milliseconds." because it is a fact guaranteed by the norm.

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/README.md
> +executes a braketest on each drive of the manipulator. This can only be done, if the robot is stopped.
I would add: "So, if you want to execute a braketest, ensure that the robot stands still."

2019-06-18 11:22 UTC, hslusarek commented on prbt_hardware_support/test/unittests/unittest_brake_test_executor.cpp
> +  ~BrakeTestExecutorTest();
Not needed -> remove

2019-06-19 07:24 UTC, martiniil commented on prbt_hardware_support/README.md
> +The prbt_hardware_support package contains files supporting the safety functions STO and SBC of the PRBT manipulator,
I removed the abbreviations here and reformulated this paragraph

2019-06-19 14:06 UTC, merged