drop unused lapack dependency
PilzDE/pilz_robots pull request #186
Opened 2019-07-19 15:32 UTC by jschleicher

The dependency is not needed by our solver so I propose to drop it.

2019-07-19 16:06 UTC, ct2034 requested changes
Can you document this somewhere, so that we know, what manual steps to take whenever we generate the code again?

2019-08-06 11:17 UTC, jschleicher commented
@ct2034 Added a quilt series to auto-apply the patches after the auto-update using your script.

2019-08-22 16:03 UTC, ct2034 commented on prbt_ikfast_manipulator_plugin/update_ikfast_plugin.sh
> -ikfast_output_path=/home/ch/ros/pilz_ws/src/pilz_robots/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_solver.cpp
nice ;-)

2019-08-22 16:03 UTC, ct2034 approved these changes
Cool! :+1:

2019-09-10 09:51 UTC, jschleicher commented on prbt_ikfast_manipulator_plugin/update_ikfast_plugin.sh
> -ikfast_output_path=/home/ch/ros/pilz_ws/src/pilz_robots/prbt_ikfast_manipulator_plugin/src/prbt_manipulator_ikfast_solver.cpp
Indeed.

2019-09-10 09:52 UTC, jschleicher commented
@ct2034 ping
Could this be merged now?

2019-10-11 13:13 UTC, merged