WIP: Separate modbus_adapter_sto and stop1_executor
PilzDE/pilz_robots pull request #222
Opened 2019-08-23 13:23 UTC by hslusarek

2019-08-26 08:03 UTC, agutenkunst requested changes
Just some minor stuff.

2019-08-26 08:03 UTC, agutenkunst commented on pilz_testutils/include/pilz_testutils/async_test.h
> +#define BARRIER3(str1, str2, str3) barricade(str1, str2, str3)
Please use BARRIER(...)

2019-08-26 08:03 UTC, agutenkunst commented on prbt_hardware_support/include/prbt_hardware_support/modbus_adapter_sto.h
> +using TUpdateStoFunc = std::function<void(const bool)>;
Why the T?

2019-08-26 08:03 UTC, agutenkunst commented on prbt_hardware_support/include/prbt_hardware_support/stop1_executor.h
> +/*
Did you rename with "git mv"?

2019-08-26 08:03 UTC, agutenkunst commented on prbt_hardware_support/test/unittests/unittest_stop1_executor.cpp
> +  TServiceCallFunc false_recover_action = []() {
Would auto work?

2019-08-26 08:03 UTC, agutenkunst commented on prbt_hardware_support/test/unittests/unittest_stop1_executor.cpp
> +  TServiceCallFunc enable_during_halt_action = [this, &adapter_sto]() {
Would auto work

2019-08-27 11:31 UTC, hslusarek commented on pilz_testutils/include/pilz_testutils/async_test.h
> +#define BARRIER3(str1, str2, str3) barricade(str1, str2, str3)
Done.

2019-08-27 11:36 UTC, hslusarek commented on prbt_hardware_support/include/prbt_hardware_support/modbus_adapter_sto.h
> +using TUpdateStoFunc = std::function<void(const bool)>;
Done.

2019-08-27 11:36 UTC, hslusarek commented on prbt_hardware_support/include/prbt_hardware_support/stop1_executor.h
> +/*
No.

2019-08-27 12:33 UTC, hslusarek commented on prbt_hardware_support/test/unittests/unittest_stop1_executor.cpp
> +  TServiceCallFunc enable_during_halt_action = [this, &adapter_sto]() {
Done.

2019-08-27 12:33 UTC, hslusarek commented on prbt_hardware_support/test/unittests/unittest_stop1_executor.cpp
> +  TServiceCallFunc false_recover_action = []() {
Done.

2019-08-27 14:11 UTC, merged