Fix/clang compiler errors
PilzDE/pilz_robots pull request #283
Opened 2019-11-12 21:09 UTC by HiddenBug

Fix clang compiler errors. The clang compiler is needed for the different sanitizer (see [Google's sanitizer GitHub repo](https://github.com/google/sanitizers)).
See also PR #281 which needs these fixes.

2019-11-15 20:02 UTC, leunMar requested changes
I approve this essentially. Only minor improvements.

2019-11-15 20:02 UTC, leunMar commented on prbt_hardware_support/test/unittests/unittest_speed_observer.cpp
> +  return static_cast<unsigned long>(i) < arg->name.size() && arg->speed.at(static_cast<size_t>(i)) <= x;
```suggestion
  return static_cast<size_t>(i) < arg->name.size() && arg->speed.at(static_cast<size_t>(i)) <= x;
```

2019-11-15 20:02 UTC, leunMar commented on prbt_hardware_support/test/unittests/unittest_speed_observer.cpp
> +  return static_cast<unsigned long>(i) < arg->name.size() && arg->speed.at(static_cast<size_t>(i)) >= x;
```suggestion
  return static_cast<size_t>(i) < arg->name.size() && arg->speed.at(static_cast<size_t>(i)) >= x;
```

2019-11-15 20:02 UTC, leunMar commented on prbt_hardware_support/test/unittests/unittest_speed_observer.cpp
> +  return static_cast<unsigned long>(i) < arg->name.size() && arg->speed.at(static_cast<size_t>(i)) >= x;
This is more consistent and makes it easier to read. Also the Matcher above (Line 144, was not changed, so I cannot review it) has two casts, where the types now should be replaced by `size_t`.

2019-11-19 09:53 UTC, leunMar commented
Please unify size_t usiage here, too:
https://github.com/PilzDE/pilz_robots/blob/f483eaed601fcf5782cf60e24b4c05c42d1440b6/prbt_hardware_support/test/unittests/unittest_speed_observer.cpp#L144

2019-11-19 10:42 UTC, HiddenBug commented
> Please unify size_t usiage here, too:
> 
> https://github.com/PilzDE/pilz_robots/blob/f483eaed601fcf5782cf60e24b4c05c42d1440b6/prbt_hardware_support/test/unittests/unittest_speed_observer.cpp#L144

Done.

2019-11-19 11:27 UTC, HiddenBug commented
@leunMar What do you think? Can we merge?

2019-11-19 12:07 UTC, leunMar approved these changes

2019-11-19 12:13 UTC, merged