Rename waitForTopic() -> waitForMessage()
PilzDE/pilz_robots pull request #291
Opened 2019-11-28 14:22 UTC by martiniil

This is more accurately describing what the function does.

2020-02-05 08:35 UTC, ct2034 requested changes

2020-02-05 08:35 UTC, ct2034 commented on pilz_utils/include/pilz_utils/wait_for_message.h
> +#endif // PILZ_UTILS_WAIT_FOR_Message_H
please capitalize this

2020-02-06 19:59 UTC, martiniil commented on pilz_utils/include/pilz_utils/wait_for_message.h
> +#endif // PILZ_UTILS_WAIT_FOR_Message_H
Thanks. Done.

2020-02-10 07:39 UTC, ct2034 approved these changes

2020-02-10 07:39 UTC, merged