WIP: Cartesian speed limitation in PilzJointTrajectoryController
PilzDE/pilz_robots pull request #296
Opened 2020-01-09 16:12 UTC by martiniil

2020-01-20 16:45 UTC, HiddenBug submitted a review, later dismissed
The architecture looks good to me. Maybe we should write down, that the controller itself can now trigger a stop 1.

2020-02-06 15:35 UTC, hslusarek commented
@martiniil PR #308 tries to integrate the velocity check into the `JointTrajectoryController`.

2020-02-12 14:08 UTC, ct2034 approved these changes
review of all, except the architecture diagram

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +The DIN EN ISO 10218-1 support is WORK IN PROGRESS!!!
```suggestion
The DIN EN ISO 10218-1 support is currently **WORK IN PROGRESS**  
```

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +- Safety controller: PSS 4000 (with special PSS 4000 program)
```suggestion
- Safety controller: PSS 4000 (with a dedicated program)
```

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +- Pushbutton unit (with emergency stop): PITgatebox
this can have various configurations

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +controllers! Currently, the PNOZmulti does not support the brake test feature
this is the first time, PNOZmulti is mentioned. Either introduce it as (legacy, unsupported) option or leave it out altogether.

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +[pilz_robots-README](https://github.com/PilzDE/pilz_robots#running-on-the-real-robot).
we could reference https://github.com/PilzDE/pilz_templates/ here

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +components supporting special safety feature.
```suggestion
components supporting the required safety features.
```

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +- Robot: Manipulator module PRBT
```suggestion
- Robot: Manipulator module PRBT 6
```

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +The `prbt_hardware_support` package provides support for the Pilz hardware
There is a video on this: https://vimeo.com/378682930 ;-)

2020-02-12 14:08 UTC, ct2034 commented on prbt_hardware_support/README.md
> +the prevailing motion is aborted and a controlled stop is performed.
```suggestion
the current motion is aborted and a controlled stop is performed.
```

2020-02-12 14:09 UTC, ct2034 requested changes
sorry, I approved by accident. Please see my previous comments

2020-03-25 09:09 UTC, martiniil commented
Merge via #308.

2020-03-25 09:09 UTC, closed without merging