Move system_info_node to prbt_support
PilzDE/pilz_robots pull request #357
Opened 2020-04-23 13:42 UTC by SansoneG

Created as per https://github.com/PilzDE/pilz_robots/pull/353#issuecomment-618282303

* Move system_info_node itself
* Move associated tests
* Add standard source-code related checks to prbt_support/CMakeLists.txt since this is the first source-code to be added
* Add new dependencies to prbt_support/package.xml
* Update Changelogs

Should we:
 [ ] Update any ReadMe?
 [ ] Remove the compiler flags that are commented out?

2020-04-23 14:02 UTC, martiniil requested changes
Looks good.

> Should we:
[ ] Update any ReadMe?

Please create a README.md for prbt_support and add a small description of the node under the headline `ROS API` analogue to https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/README.md

>[ ] Remove the compiler flags that are commented out?

Please uncomment all flags.

2020-04-23 19:25 UTC, ct2034 approved these changes

2020-04-24 09:11 UTC, cdoehn commented
@martiniil Could you please review the README

2020-04-24 09:15 UTC, martiniil requested changes

2020-04-24 09:15 UTC, martiniil commented on prbt_support/README.md
> +  - Holds information about joint firmware.
```suggestion
  - Read CANOpen object holding firmware information.
```

2020-04-24 09:15 UTC, martiniil commented on prbt_support/CMakeLists.txt
> +#add_definitions(-Wpedantic)
```suggestion
add_definitions(-Wall)
add_definitions(-Wextra)
add_definitions(-Wno-unused-parameter)
add_definitions(-Werror)
add_definitions(-std=c++11)
add_definitions(-Wconversion) # At least this line needs to be below find_package to keep
                              #  the flag away from the gmock build
add_definitions(-Wpedantic)
```

2020-04-24 12:27 UTC, martiniil approved these changes

2020-04-24 12:30 UTC, merged