Add new package prbt_gazebo
PilzDE/pilz_robots pull request #36
Opened 2018-12-18 12:02 UTC by agutenkunst

as example how to use our model in combination with Gazebo

2018-12-18 13:04 UTC, martiniil requested changes
A travis job failed. Can you have a look at it?

2018-12-18 13:04 UTC, martiniil commented on prbt_gazebo/CHANGELOG.rst
> +* Created trajectory generation package with ptp, lin, circ and blend planner
Please adapt changelog

2018-12-18 13:04 UTC, martiniil commented on prbt_gazebo/README.md
> +Package providing a launch which can be used to launch Gazebo with the
launch <i>file</i>?

2018-12-18 13:04 UTC, martiniil commented on prbt_gazebo/launch/sim_prbt_gazebo.launch
> +you may not use this file except in compliance with the License.
License file missing

2018-12-18 13:20 UTC, agutenkunst commented on prbt_gazebo/launch/sim_prbt_gazebo.launch
> +you may not use this file except in compliance with the License.
Fixed.

2018-12-18 13:21 UTC, agutenkunst commented on prbt_gazebo/README.md
> +Package providing a launch which can be used to launch Gazebo with the
Fixed.

2018-12-18 13:22 UTC, agutenkunst commented on prbt_gazebo/CHANGELOG.rst
> +* Created trajectory generation package with ptp, lin, circ and blend planner
Fixed.

2018-12-18 14:01 UTC, agutenkunst commented on prbt_gazebo/CHANGELOG.rst
> +* Created trajectory generation package with ptp, lin, circ and blend planner
Adapted.

2018-12-19 07:23 UTC, martiniil approved these changes

2018-12-19 07:23 UTC, merged