Make test-subfolder-names consistent
PilzDE/pilz_robots pull request #380
Opened 2020-05-07 12:39 UTC by martiniil

In some packages, we have the naming `unittests`, in other packages `unit_tests`.

- Rename `unittests` -> `unit_tests`,
- same for all integration- and acceptance-test folders.

2020-05-08 08:47 UTC, cdoehn requested changes
Not all occurances of unittests and acceptancetests are changed to unit_tests and acceptance_tests.
The necessary changes are located here:

prbt_ikfast_manipulator_plugin/patches/add-unittests.patch:+    test/unittests/tst_${PROJECT_NAME}.test
prbt_ikfast_manipulator_plugin/patches/add-unittests.patch:+    test/unittests/tst_${PROJECT_NAME}.cpp
prbt_hardware_support/rosdoc.yaml:  exclude_patterns: '*/test/acceptancetests/*'

2020-05-08 09:17 UTC, martiniil commented
> Not all occurances of unittests and acceptancetests are changed to unit_tests and acceptance_tests.
> The necessary changes are located here:
> 
> prbt_ikfast_manipulator_plugin/patches/add-unittests.patch:+ test/unittests/tst_${PROJECT_NAME}.test
> prbt_ikfast_manipulator_plugin/patches/add-unittests.patch:+ test/unittests/tst_${PROJECT_NAME}.cpp
> prbt_hardware_support/rosdoc.yaml: exclude_patterns: '_/test/acceptancetests/_'

Thank you. I committed the changes.

2020-05-11 06:43 UTC, SansoneG commented
Should we also change the prefixes of the files in `prbt_ikfast_manipulator_plugin/test/unit_tests` from `tst` to `unittest`, or is that a separate PR?
This seems to be the only place where the prefixes don't follow that convention.

2020-05-11 08:16 UTC, SansoneG approved these changes

2020-05-11 09:23 UTC, cdoehn approved these changes

2020-05-11 09:23 UTC, merged