longer timeout for modbus responses
PilzDE/pilz_robots pull request #97
Opened 2019-04-03 10:42 UTC by ct2034

I tested it with different ethernet adapters: This timeout can always be met.

2019-04-03 11:25 UTC, jschleicher reviewed
What about the Changelog?

2019-04-03 11:43 UTC, hslusarek commented
If we change this Timeout, do we have to change the time used for the break trajectory?

2019-04-03 11:47 UTC, hslusarek commented
Why do you merge it into melodic? Our develop branch is still kinetic until is officially moved to melodic.

2019-04-03 12:05 UTC, jschleicher commented
> If we change this Timeout, do we have to change the time used for the break trajectory? See [here](https://github.com/PilzDE/pilz_robots/blob/5913a9009b8aef642b01c9000c80d1227d9a0643/prbt_hardware_support/include/prbt_hardware_support/sto_modbus_adapter.h#L94).

No, the brake time is determined by the maximum deceleration of the axes and must not be reduced. Where is the overall stop time documented that is set inside the PNOZ safety program?

2019-04-17 11:53 UTC, jschleicher requested changes
What about the Changelog?
Why do you merge into melodic? Would you mind adding a note to the README as in PilzDE/pilz_industrial_motion#150 about the default development branch? Most probably you need a merge of the current kinetic-branch into melodic before changing the default branch...

2019-04-18 06:02 UTC, agutenkunst commented
I need to know a bit more about the reason behind this PR...

2019-04-18 07:49 UTC, agutenkunst commented
Also see https://github.com/PilzDE/pilz_robots/pull/97 related?

2019-04-23 13:30 UTC, ct2034 commented
> I need to know a bit more about the reason behind this PR...

@agutenkunst In some configurations, the modbus communication was timing out with the old timeout. This led probably to #81. If the problem in #81 still exists, we will look at it again.
Can you please check @JonathanGruner

2019-04-23 21:26 UTC, JonathanGruner commented
Hi I can check it next week when back from vacations, until then I assume increasing the timeout to 20 ms is good enough, there were no modbus problems in Chicago..

2019-04-29 08:31 UTC, jschleicher approved these changes
@agutenkunst Thanks for asking about the rationale:

#93 showed modbus disconnects with PSS4000 (obviously slower reactions than the PNOZmulti) and ct2034 experienced disconnects with USB-Ethernet-Adapters (PNOZ-multi but slower than internal pci network adapters). Both issues were solved when increasing the timeout to 20ms. As a follow-up the delay in the safety program needs to be increased by 10ms (and documented) as well!

2019-05-02 07:11 UTC, hslusarek commented
@ct2034 Can we merge?

2019-05-02 09:30 UTC, jschleicher commented
@hslusarek 
:+1:  from my side. Please merge.

2019-05-02 15:01 UTC, merged